name: Java CI with Gradle

on:
  push:
    paths:
      - "src/**"
      - ".github/**"
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Cache gradle files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./.gradle/loom-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle', 'gradle.properties', '**/*.accesswidener') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build

      - uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/libs/

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    strategy:
      matrix:
        release-branch:
          - '1.15.2'

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.release-branch }}
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Upload to the Github release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/libs/*.jar
            !build/libs/*-dev.jar
            !build/libs/*-sources.jar
