name: Java CI with Gradle

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    strategy:
      matrix:
        release-branch:
          - '1.15.2'
          - '1.16.5'

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.release-branch }}
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build
        env:
          BUILD_RELEASE: ${{ github.event.prerelease == false }}

      - uses: actions/upload-artifact@v2
        with:
          name: [${{ matrix.release-branch }}] release-artifacts
          path: build/libs/

      - name: Upload to the Github release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'build/libs/*.jar;!build/libs/*-dev.jar;!build/libs/*-sources.jar'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
